# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: 继续阅读
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics: UA-49483742-2
favicon: /favicon.png
disqus_shortname: jokcyblog
twitter:
google_plus:
fb_admins:
fb_app_id: